//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;

    public partial class StudentsDataSet : System.Data.DataSet
    {
        private СтудентыDataTable tableСтуденты;
        private СпециальностиDataTable tableСпециальности;

        public StudentsDataSet()
        {
            this.InitClass();
        }

        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public СтудентыDataTable Студенты
        {
            get
            {
                return this.tableСтуденты;
            }
        }

        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public СпециальностиDataTable Специальности
        {
            get
            {
                return this.tableСпециальности;
            }
        }

        private void InitClass()
        {
            this.DataSetName = "StudentsDataSet";
            this.tableСтуденты = new СтудентыDataTable();
            this.tableСпециальности = new СпециальностиDataTable();
            base.Tables.Add(this.tableСтуденты);
            base.Tables.Add(this.tableСпециальности);
        }

        public partial class СтудентыDataTable : System.Data.DataTable
        {
            private System.Data.DataColumn columnКод_студента;
            private System.Data.DataColumn columnФИО;
            private System.Data.DataColumn columnПол;
            private System.Data.DataColumn columnДата_рождения;
            private System.Data.DataColumn columnРодители;
            private System.Data.DataColumn columnАдрес;
            private System.Data.DataColumn columnТелефон;
            private System.Data.DataColumn columnПаспортные_данные;
            private System.Data.DataColumn columnНомер_зачётки;
            private System.Data.DataColumn columnДата_поступления;
            private System.Data.DataColumn columnГруппа;
            private System.Data.DataColumn columnКурс;
            private System.Data.DataColumn columnКод_специальности;
            private System.Data.DataColumn columnОчная_форма_обучения;

            public СтудентыDataTable()
            {
                this.TableName = "Студенты";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }

            private void InitClass()
            {
                this.columnКод_студента = new System.Data.DataColumn("Код студента", typeof(long), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnКод_студента);
                this.columnФИО = new System.Data.DataColumn("ФИО", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnФИО);
                this.columnПол = new System.Data.DataColumn("Пол", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnПол);
                this.columnДата_рождения = new System.Data.DataColumn("Дата рождения", typeof(DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnДата_рождения);
                this.columnРодители = new System.Data.DataColumn("Родители", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnРодители);
                this.columnАдрес = new System.Data.DataColumn("Адрес", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnАдрес);
                this.columnТелефон = new System.Data.DataColumn("Телефон", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnТелефон);
                this.columnПаспортные_данные = new System.Data.DataColumn("Паспортные данные", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnПаспортные_данные);
                this.columnНомер_зачётки = new System.Data.DataColumn("Номер зачётки", typeof(long), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnНомер_зачётки);
                this.columnДата_поступления = new System.Data.DataColumn("Дата поступления", typeof(DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnДата_поступления);
                this.columnГруппа = new System.Data.DataColumn("Группа", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnГруппа);
                this.columnКурс = new System.Data.DataColumn("Курс", typeof(byte), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnКурс);
                this.columnКод_специальности = new System.Data.DataColumn("Код специальности", typeof(long), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnКод_специальности);
                this.columnОчная_форма_обучения = new System.Data.DataColumn("Очная форма обучения", typeof(bool), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnОчная_форма_обучения);
                this.columnКод_студента.AutoIncrement = true;
                this.columnКод_студента.AllowDBNull = false;
                this.columnКод_студента.ReadOnly = true;
                this.columnКод_студента.Unique = true;
            }

            public СтудентыRow NewСтудентыRow()
            {
                return ((СтудентыRow)(this.NewRow()));
            }

            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder)
            {
                return new СтудентыRow(builder);
            }

            protected override System.Type GetRowType()
            {
                return typeof(СтудентыRow);
            }

            public partial class СтудентыRow : System.Data.DataRow
            {
                private СтудентыDataTable tableСтуденты;

                internal СтудентыRow(System.Data.DataRowBuilder rb) : base(rb)
                {
                    this.tableСтуденты = ((СтудентыDataTable)(this.Table));
                }

                public long Код_студента
                {
                    get
                    {
                        return ((long)(this[this.tableСтуденты.columnКод_студента]));
                    }
                    set
                    {
                        this[this.tableСтуденты.columnКод_студента] = value;
                    }
                }

                public string ФИО
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСтуденты.columnФИО]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'ФИО\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnФИО] = value;
                    }
                }

                public string Пол
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСтуденты.columnПол]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Пол\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnПол] = value;
                    }
                }

                public System.DateTime Дата_рождения
                {
                    get
                    {
                        try
                        {
                            return ((System.DateTime)(this[this.tableСтуденты.columnДата_рождения]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Дата рождения\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnДата_рождения] = value;
                    }
                }

                public string Родители
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСтуденты.columnРодители]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Родители\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnРодители] = value;
                    }
                }

                public string Адрес
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСтуденты.columnАдрес]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Адрес\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnАдрес] = value;
                    }
                }

                public string Телефон
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСтуденты.columnТелефон]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Телефон\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnТелефон] = value;
                    }
                }

                public string Паспортные_данные
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСтуденты.columnПаспортные_данные]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Паспортные данные\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnПаспортные_данные] = value;
                    }
                }

                public long Номер_зачётки
                {
                    get
                    {
                        try
                        {
                            return ((long)(this[this.tableСтуденты.columnНомер_зачётки]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Номер зачётки\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnНомер_зачётки] = value;
                    }
                }

                public System.DateTime Дата_поступления
                {
                    get
                    {
                        try
                        {
                            return ((System.DateTime)(this[this.tableСтуденты.columnДата_поступления]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Дата поступления\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnДата_поступления] = value;
                    }
                }

                public string Группа
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСтуденты.columnГруппа]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Группа\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnГруппа] = value;
                    }
                }

                public byte Курс
                {
                    get
                    {
                        try
                        {
                            return ((byte)(this[this.tableСтуденты.columnКурс]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Курс\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnКурс] = value;
                    }
                }

                public long Код_специальности
                {
                    get
                    {
                        try
                        {
                            return ((long)(this[this.tableСтуденты.columnКод_специальности]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Код специальности\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnКод_специальности] = value;
                    }
                }

                public bool Очная_форма_обучения
                {
                    get
                    {
                        try
                        {
                            return ((bool)(this[this.tableСтуденты.columnОчная_форма_обучения]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Очная форма обучения\' в таблице \'Студенты\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСтуденты.columnОчная_форма_обучения] = value;
                    }
                }
            }
        }

        public partial class СпециальностиDataTable : System.Data.DataTable
        {
            private System.Data.DataColumn columnКод_специальности;
            private System.Data.DataColumn columnНаименование_специальности;
            private System.Data.DataColumn columnОписание_специальности;

            public СпециальностиDataTable()
            {
                this.TableName = "Специальности";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }

            private void InitClass()
            {
                this.columnКод_специальности = new System.Data.DataColumn("Код специальности", typeof(long), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnКод_специальности);
                this.columnНаименование_специальности = new System.Data.DataColumn("Наименование специальности", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnНаименование_специальности);
                this.columnОписание_специальности = new System.Data.DataColumn("Описание специальности", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnОписание_специальности);
                this.columnКод_специальности.AutoIncrement = true;
                this.columnКод_специальности.AllowDBNull = false;
                this.columnКод_специальности.ReadOnly = true;
                this.columnКод_специальности.Unique = true;
            }

            public СпециальностиRow NewСпециальностиRow()
            {
                return ((СпециальностиRow)(this.NewRow()));
            }

            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder)
            {
                return new СпециальностиRow(builder);
            }

            protected override System.Type GetRowType()
            {
                return typeof(СпециальностиRow);
            }

            public partial class СпециальностиRow : System.Data.DataRow
            {
                private СпециальностиDataTable tableСпециальности;

                internal СпециальностиRow(System.Data.DataRowBuilder rb) : base(rb)
                {
                    this.tableСпециальности = ((СпециальностиDataTable)(this.Table));
                }

                public long Код_специальности
                {
                    get
                    {
                        return ((long)(this[this.tableСпециальности.columnКод_специальности]));
                    }
                    set
                    {
                        this[this.tableСпециальности.columnКод_специальности] = value;
                    }
                }

                public string Наименование_специальности
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСпециальности.columnНаименование_специальности]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Наименование специальности\' в таблице \'Специальности\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСпециальности.columnНаименование_специальности] = value;
                    }
                }

                public string Описание_специальности
                {
                    get
                    {
                        try
                        {
                            return ((string)(this[this.tableСпециальности.columnОписание_специальности]));
                        }
                        catch (System.InvalidCastException e)
                        {
                            throw new System.Data.StrongTypingException("Значение для столбца \'Описание специальности\' в таблице \'Специальности\' равно DBNull.", e);
                        }
                    }
                    set
                    {
                        this[this.tableСпециальности.columnОписание_специальности] = value;
                    }
                }
            }
        }
    }
}

